openmainframeproject/tac

proposed_projects/Close the gap of s390x packages in SUSE Package Hub.md
=> Close the gap of s390x packages in SUSE Package Hub proposal submission

proposed_projects/Legacy.md
Signed-off-by: philo-math <26297035+philo-math@users.noreply.github.com>
=> Correcting the markdown errors: to improve the asthetics.

proposed_projects/Document the deployment of Kubernetes cluster on IBM LinuxONE.md
=> Document the deployment of Kubernetes cluster on IBM LinuxONE proposal submission

proposed_projects/Build components of a containerized implementation of Cloud Foundry on Z.md
=> Submit Cloud Foundry intern project proposal

projects/internship/past.md
Signed-off-by: philo-math <26297035+philo-math@users.noreply.github.com>
=> Correcting the column name of project and mentors.

proposed_projects/Increase the number of s390x packages in SUSE Package Hub.md
=> Add mentor to Package Hub proposal

process/code_of_conduct.md, process/example_governance.md, process/project_stages.md, process/proposal_process.md, projects/proposals/TEMPLATE.md
=> Proposed TSC process defintion for TSC review

proposed_projects/Cloud_Foundry_Operator_for_Kubernetes_on_Z.md
=> Submit Cloud Foundry Operator for Kubernetes on Z project proposal

proposed.md
Signed-off-by: Rajat Soni <rajat.tcp@gmail.com>
=> fixed-link for Hybrid Blockchain project in proposed.md

proposed.md, proposed_projects/Zowe Features Addition.md
Matt Hogstrom is willing to be mentor for this internship project.
=> Adding Zowe Feature Addition project.

meetings/s390x-oss-ecosystem-anaylsis/inconsistent.txt, meetings/s390x-oss-ecosystem-anaylsis/missing.txt, meetings/s390x-oss-ecosystem-anaylsis/proposed-focus-projects.md
=> Updates from 20190507 meeting

README.md
=> Add CII badge status for hosted projects

README.md
=> Update calendar link

meetings/s390x-oss-ecosystem-anaylsis/proposed-focus-projects.md
=> Updated based on meeting 20190521

process/contribution_guidelines.md
=> Add links to DCO signoff tools

meetings/20190613.md
=> Adding link to TSC email list message

proposed_projects/ComplianceEngine-2019.md
=> Fixed typo

meetings/20190613.md, meetings/20190711.md
Add proposed meeting agenda for 2019-07-11
=> Added meeting notes and recording from 2019-06-13

README.md
=> Changed z/OS Workflows to Zorow

README.md
=> Updated for Feilong

meetings/20190815.md
=> Rename meeting agenda to 20190815. Update link for project proposal.

meetings/20190814.md
=> Fix date of TSC meeting

meetings/20190814.md, meetings/20190919.md
=> Add agenda for 20190919 and notes from 20190814

proposed.md, proposed_projects/LuaJIT_s390x_support.md
Signed-off-by: Siddhesh Poyarekar <siddhesh@gotplt.org>
=> Propose project for LuaJIT S390x maintenance

proposed_projects/LuaJIT_s390x_support.md
The description for the proposal was a bit vague, so made it more specific to make it clear that the mentee would be implementing a JIT compiler for S390x.  I also replaced the CI link to one that doesn't get garbage collected every week.
Signed-Off-By: Siddhesh Poyarekar <siddhesh@gotplt.org>
=> Update LuaJIT S390x proposal

README.md
=> Add Open Z Systems Exchange as an incubation project

meetings/20190919.md
=> Add ZJenkins project proposal and Open Z Systems Exchange to agenda.

meetings/20190919.md
=> Add additional project proposal

meetings/20190919.md
=> Add agenda item for TSC > TAC name change

README.md
=> Add zJenkins and update Rocket TSC rep

README.md
=> Change TSC -> TAC

meetings/20191212.md
=> Add meeting dialin details to agenda doc

README.md
=> Update TAC members and s/TSC/TAC/g

meetings/20200213.md
=> Add section 'Projects potentially to be proposed'

process/example_governance.md
=> Tweaked to match the process in Github

process/example_readme.md, process/new_project_checklist.md
=> Add TSC record keeping section and README as an action.

.github/workflows/create_agenda.yml
=> Adjust TAC meeting date

process/github-policy.md
=> Add TOC and best practice section

process/project_benefits_by_stage.md
=> Create Project Benefits by Stage matrix

.github/ISSUE_TEMPLATE/ambassador-application.md, process/ambassadors.md
=> Ambassador program proposal

meetings/20201112.md
=> TAC meeting notes from 20201111

process/github-policy.md
Co-authored-by: Jenn Francis <Jenn.Francis@ibm.com>
=> Add Github usage and markdown instructions

.github/ISSUE_TEMPLATE/meeting.md
=> Add Sean Grady as Zowe rep

process/conformance_programs.md, process/project_benefits_by_stage.md
=> Add details on conformance programs

_data/tacmembers.csv
Signed-off-by: Tatiana Balaburkina <tbalaburkina@rocketsoftware.com>
=> Update TAC members

.github/ISSUE_TEMPLATE/meeting.md
=> Change Rocket Software TAC rep

_data/projects.csv
=> Update COBOL Working Group review date

process/review_cycle.md
=> Fix date formatting on Review Cycle page

.github/ISSUE_TEMPLATE/meeting.md
=> Fixed TAC meeting template

.github/workflows/create_agenda.yml
=> Fix TAC meeting cadence date

meetings/2022-01-13.md
=> Fix typos and naming convention

process/project_stages.md
=> Add date and change from CII -> OpenSSF

.github/workflows/updatetacmembers.py, .github/workflows/updatetacmembers.yml
=> Fix TAC members build

meetings/2023-01-26.md
=> Add 2023-01-26 notes

programs/infrastructure/plan.md
The one thing missing that I just realized is there was nothing about migrating the CBT environment, or any other environment (if there are), to the new box.
=> Update plan.md with Migration Note
